server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:8083
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
      bindings:
        broadcastGreetings:
          destination: greetings-pub-sub
        directGreetings:
          destination: greetings-p2p